services:
  browsertests:
    environment:
      - BROWSER=${BROWSER:-chrome}
      - REMOTE_URL=http://${SELENIUM_HOSTNAME:-selenium-browser}:4444/wd/hub
      - BASE_URL=${BASE_URL:-https://the-internet.herokuapp.com}
    depends_on:
      - seleniumbrowser

  seleniumbrowser:
    # The selenium/standalone-chromium image is multiplatform (arm64)
    image: ${SELENIUM_IMAGE:-selenium/standalone-chromium:latest}
    container_name: ${SELENIUM_HOSTNAME:-selenium-browser}
    shm_size: 4gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
      - "7900:7900"
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    healthcheck:
      test: ["CMD-SHELL", '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444']
      interval: 15s
      timeout: 30s
      retries: 5
