services:
  browsertests:
    image: brianjbayer/sample-login-geb-spock:${BROWSERTESTS_TAG:-latest}
    container_name: ${BROWSERTESTS_HOSTNAME:-browsertests}
    environment:
      - LOGIN_USERNAME
      - LOGIN_PASSWORD
      - BROWSER
      - REMOTE_URL
      - HEADLESS
      - BASE_URL
